---
- name: AR-OPS-AUTO
  hosts: localhost
  tasks:
  - name: VM-4
    os_server:
       state: present
       name: vm4
       image: "Ubuntu-18.04"
       key_name: AR-AD
       timeout: 200
       flavor: 387eba78-858d-46f4-83c7-678abc0596e3
       auto_ip: no
       network: 9d85eea4-50eb-4aba-a12e-0d89de56cb4b
       security_groups: default
       meta:
         os: ubuntu

  - name: VM-5
    os_server:
       state: present
       name: vm5
       image: "Ubuntu-18.04"
       key_name: AR-AD
       timeout: 200
       flavor: 387eba78-858d-46f4-83c7-678abc0596e3
       auto_ip: no
       network: 9d85eea4-50eb-4aba-a12e-0d89de56cb4b
       security_groups: default
       meta:
         os: ubuntu

  - name: VM-5
    os_server:
       state: present
       name: vm5
       image: "Ubuntu-18.04"
       key_name: AR-AD
       timeout: 200
       flavor: 387eba78-858d-46f4-83c7-678abc0596e3
       auto_ip: no
       network: 9d85eea4-50eb-4aba-a12e-0d89de56cb4b
       security_groups: default
       meta:
         os: ubuntu             

