---
- name: AR-OPS-AUTO
  hosts: localhost
  tasks:
  - name: VM-1
    os_server:
       state: present
       name: vm1
       image: "Ubuntu-20.04"
       key_name: AR-AD
       timeout: 200
       flavor: 96eede79-68d8-4086-921e-57133de73c2b
       auto_ip: no
       network: 7ef4c191-a7dd-4b75-8f9d-31df32b86291
       security_groups: default
       meta:
         os: ubuntu

  - name: VM-2
    os_server:
       state: present
       name: vm3
       image: "Ubuntu-20.04"
       key_name: AR-AD
       timeout: 200
       flavor: 96eede79-68d8-4086-921e-57133de73c2b
       auto_ip: no
       network: 7ef4c191-a7dd-4b75-8f9d-31df32b86291
       security_groups: default
       meta:
         os: ubuntu

  - name: VM-3
    os_server:
       state: present
       name: vm3
       image: "Ubuntu-20.04"
       key_name: AR-AD
       timeout: 200
       flavor: 96eede79-68d8-4086-921e-57133de73c2b
       auto_ip: no
       network: 7ef4c191-a7dd-4b75-8f9d-31df32b86291
       security_groups: default
       meta:
         os: ubuntu             

